name: car_tool_instruct
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - distro==1.9.0
      - filelock==3.20.3
      - fsspec==2026.1.0
      - google-auth==2.47.0
      - google-genai==1.57.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - joblib==1.5.3
      - nltk==3.9.2
      - numpy==2.4.1
      - packaging==25.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - rouge-score==0.1.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - six==1.17.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - tokenizers==0.22.2
      - tqdm==4.67.1
      - transformers==4.57.5
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - websockets==15.0.1
